<?php
session_start();require_once __DIR__."/config/koneksi.php";
if(!isset($_SESSION['user'])){header("Location:login.php");exit;}
$uid=(int)$_SESSION['user']['id'];
$stmt=$conn->prepare("SELECT a.*, b.bid_amount AS my_bid, b.bid_time FROM auctions a JOIN bids b ON b.auction_id=a.id AND b.user_id=? WHERE b.id=(SELECT b2.id FROM bids b2 WHERE b2.auction_id=a.id AND b2.user_id=? ORDER BY b2.bid_amount DESC,b2.bid_time DESC LIMIT 1) ORDER BY b.bid_time DESC");$stmt->bind_param("ii",$uid,$uid);$stmt->execute();$result=$stmt->get_result();
function rupiah($n){return 'Rp '.number_format((float)$n,0,',','.');}function e($s){return htmlspecialchars((string)$s,ENT_QUOTES,'UTF-8');}
?>
<!DOCTYPE html><html lang="id"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Riwayat — LelangKita</title>
<style>
*{box-sizing:border-box}body{margin:0;font-family:Segoe UI,Arial;background:#f5f7fb;color:#1b222c}.container{width:min(1050px,92%);margin:auto}.nav{background:#fff;border-bottom:1px solid #e6eaf1}.navin{height:70px;display:flex;justify-content:space-between;align-items:center}.logo{font-size:23px;font-weight:900}.logo span{color:#6d4aff}.nav a{margin-left:15px;color:#606977;font-weight:700}.main{padding:45px 0}.head h1{margin:0 0 6px;font-size:34px}.muted{color:#77818f}.table{margin-top:25px;background:#fff;border:1px solid #e5e9f0;border-radius:20px;overflow:auto;box-shadow:0 15px 40px #1d27300b}table{width:100%;border-collapse:collapse;min-width:750px}th,td{text-align:left;padding:18px;border-bottom:1px solid #edf0f4}th{background:#fafbfc;color:#697281;font-size:13px;text-transform:uppercase}tr:last-child td{border-bottom:0}.badge{padding:7px 10px;border-radius:99px;font-size:12px;font-weight:900}.green{background:#e8faf0;color:#15804b}.gray{background:#eef0f4;color:#69717e}.yellow{background:#fff5d9;color:#896300}.btn{display:inline-block;padding:9px 12px;border-radius:10px;background:#6d4aff;color:#fff;font-weight:800}
.empty{padding:60px;background:#fff;border:1px dashed #d6dbe4;border-radius:20px;text-align:center}
</style></head><body><nav class="nav"><div class="container navin"><a class="logo" href="index.php">🔨 Lelang<span>Kita</span></a><div><a href="index.php">Beranda</a><a href="logout.php">Keluar</a></div></div></nav><main class="main"><div class="container"><div class="head"><h1>Riwayat Lelang</h1><p class="muted">Pantau penawaran yang pernah kamu ikuti dan pembayaran kemenangan.</p></div>
<?php if($result->num_rows):?><div class="table"><table><thead><tr><th>Produk</th><th>Bid Saya</th><th>Harga Tertinggi</th><th>Status</th><th>Aksi</th></tr></thead><tbody>
<?php while($r=$result->fetch_assoc()): $winner=(int)$r['winner_user_id']===$uid && $r['winner_status']==='ditentukan'; $payment=null; if($winner){$p=$conn->prepare("SELECT * FROM payments WHERE auction_id=? AND user_id=? ORDER BY id DESC LIMIT 1");$p->bind_param("ii",$r['id'],$uid);$p->execute();$payment=$p->get_result()->fetch_assoc();} ?>
<tr><td><strong><?=e($r['title'])?></strong><br><small class="muted"><?=date('d/m/Y H:i',strtotime($r['bid_time']))?></small></td><td><?=rupiah($r['my_bid'])?></td><td><?=rupiah($r['current_price'])?></td><td><?php if($winner):?><span class="badge green">🏆 Menang</span><?php elseif($r['status']==='aktif'):?><span class="badge green">Aktif</span><?php else:?><span class="badge gray">Selesai</span><?php endif;?></td><td><?php if($winner && (!$payment || $payment['payment_status']!=='paid')):?><a class="btn" href="pembayaran.php?id=<?=$r['id']?>">💳 Bayar</a><?php elseif($winner):?><span class="badge green">Lunas</span><?php else:?><a class="btn" href="detail.php?id=<?=$r['id']?>">Detail</a><?php endif;?></td></tr>
<?php endwhile;?></tbody></table></div><?php else:?><div class="empty"><div style="font-size:48px">🔨</div><h3>Belum ada riwayat</h3><p class="muted">Ikuti salah satu lelang untuk melihat aktivitasmu di sini.</p><a class="btn" href="index.php">Lihat Lelang</a></div><?php endif;?>
</div></main></body></html>
